title:              "SUJILOG"
tagline:            "경험주의자 마케터의 기록로그"
email:              "sookzyy@gmail.com"
description:        "일 하는 것도 노는 것도 좋아합니다. 그 가운데 보고 느낀 모든 경험을 공유합니다."
author:             "SUJI"
baseurl:            "/"
url:                "https://sujilog.com"
locale:             "ko_KR"
thumbnail:          "/img/header.png"

# Social Profiles
instagram_username: instagram_username
facebook_username:  soozyy

  # 블로그 disqus shortname
disqus:
shortname: sujilog-com

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
